FROM postgres:latest

COPY migrations /docker-entrypoint-initdb.d/

# Устанавливаем переменные окружения для PostgreSQL
ENV POSTGRES_DB=socialnetwork
ENV POSTGRES_USER=kirilllesniak
ENV POSTGRES_PASSWORD=les2005



